In [32]:
tensor = torch.arange(12 * 185 * 2).reshape(12, 185, 2)
reshaped = tensor.flatten().view(185, 24)

# Now reverse the reshape
restored_tensor = reshaped.view(12, 185, 2)

In [33]:
reshaped.shape

torch.Size([185, 24])

In [29]:
import torch
action_all_=torch.randn(12, 5, 2)
print(action_all_)
action_all_33=action_all_.reshape(-1, 2)
# print(action_all_33)
print(action_all_.permute(1, 0, 2).flatten(1, 2))

tensor([[[-0.4316, -0.6352],
         [-0.9048, -0.9134],
         [ 0.2401,  0.0957],
         [ 1.4674, -0.3444],
         [ 0.4895, -0.5367]],

        [[-0.4495,  1.0845],
         [-0.9482,  1.0846],
         [ 2.0148,  0.4340],
         [ 0.7261,  0.8908],
         [-0.8548,  1.5030]],

        [[ 2.3909, -0.1651],
         [ 0.0828,  0.1069],
         [-1.4291, -1.1401],
         [ 1.1533, -0.5935],
         [-1.0427,  0.2420]],

        [[-0.1336,  0.4190],
         [-1.7070,  0.3842],
         [ 1.7277, -1.0079],
         [-0.8909,  0.2390],
         [-0.2322, -1.1639]],

        [[ 0.9683,  0.5249],
         [-0.9901,  0.6834],
         [-1.4758,  1.0990],
         [ 0.0723,  0.7726],
         [-0.0356, -0.4092]],

        [[-0.0744,  1.9929],
         [-1.4119,  0.2734],
         [-1.8657, -1.3232],
         [ 0.4634,  1.6392],
         [ 0.7046,  1.2027]],

        [[-0.7631, -0.0551],
         [-1.1621, -0.8250],
         [-0.5130,  0.6110],
         [-0.8107,  1.8389],
  

In [10]:
import torch
action_all_=torch.randn(12, 185, 2)
aha=action_all_.permute(1,0,2)
print(aha.shape)
aha.reshape(185*12,2).shape

torch.Size([185, 12, 2])


torch.Size([2220, 2])

In [14]:
x = torch.tensor([[1, 2], [3, 4], [5, 6]])
print("Original tensor:")
print(x)

# Flatten the tensor
flattened_x = x.flatten()
reshaped_x = flattened_x.reshape(3, 2)
print("Reshaped tensor:")
print(reshaped_x)

Original tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])
Reshaped tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [13]:
import torch

# Original tensor
x = torch.randn(185, 12, 2)

# Flatten dimensions 1 and 2
flattened_x = x.permute(1,0,2).flatten(1, 2)

# Reshape back to the original shape
reshaped_x = flattened_x.reshape(185, 12, 2)
# reshaped_x=reshaped_x.permute(1,0,2)
# Check if the reshaped tensor is the same as the original
print(torch.equal(x, reshaped_x))  # This should print True


False


In [6]:
import torch

# Assuming A is your original tensor with shape (12, 185, 2)
A = [torch.randn(185, 2) for i in range(12)]

# Concatenating A along dim=0, which flattens the first two dimensions
B = torch.cat(A, dim=0)  # This operation actually doesn't change anything because there's only one tensor
# B = B.view(-1, 2)          # Reshape to flatten into shape (2220, 2)

# To reverse the operation, reshape B back to the shape of A
A_restored = B.view(12, 185, 2)
identical = all(torch.equal(a, b) for a, b in zip(A, A_restored))
# Check if the restored tensor is exactly the same as the original
print("A is equal to A_restored:", identical)

A is equal to A_restored: True


In [9]:
log_probs=torch.randn(15)
print(log_probs)
log_probs=torch.reshape(log_probs, (5,3))
log_probs=log_probs.cumsum(dim=1)
print(log_probs)
log_probs=torch.reshape(log_probs, (15,))
log_probs

tensor([ 0.1880, -0.0449,  0.6468, -1.4552, -0.8197, -0.2678, -0.1753, -0.3379,
         0.7678,  0.4359, -0.4040,  0.5942, -0.4646,  0.6009, -1.2351])
tensor([[ 0.1880,  0.1431,  0.7899],
        [-1.4552, -2.2749, -2.5427],
        [-0.1753, -0.5133,  0.2545],
        [ 0.4359,  0.0319,  0.6260],
        [-0.4646,  0.1363, -1.0988]])


tensor([ 0.1880,  0.1431,  0.7899, -1.4552, -2.2749, -2.5427, -0.1753, -0.5133,
         0.2545,  0.4359,  0.0319,  0.6260, -0.4646,  0.1363, -1.0988])

In [3]:
best_ade=10
def finc():
    global best_ade
    print(best_ade)
    for i in range(10):
        best_ade += best_ade +i
finc()
finc()
finc()
finc()

10
11253
11524085
11800664053


In [9]:
import torch

# Case 1: Single tensor
tensor = torch.randn(1, 3, 4)  # Example tensor with shape [2, 3, 4]
tensor2=torch.cat((tensor,tensor), dim=0)
flattened_tensor = tensor2.flatten(0,1)

print("Case 1 - Single Tensor Flattened Shape:", flattened_tensor.shape)

# Case 2: Sequence of tensors that would form the same shape
tensor_seq = [tensor, tensor]  # Each tensor in the sequence has shape [1, 3, 4]
concatenated_then_flattened = torch.cat(tensor_seq, dim=0).flatten(0,1)

print("Case 2 - Concatenated Then Flattened Shape:", concatenated_then_flattened.shape)

# Test equivalence
# The flattened shapes should be the same if the tensors in tensor_seq collectively have the same shape as `tensor`
# Note: This equivalence is in terms of shape; the actual values will differ due to random initialization
print("Are vectors equivalent?", flattened_tensor.shape == concatenated_then_flattened.shape)

Case 1 - Single Tensor Flattened Shape: torch.Size([6, 4])
Case 2 - Concatenated Then Flattened Shape: torch.Size([6, 4])
Are shapes equivalent? True


In [8]:
import torch
torch.set_num_threads(32)

/home/ssukup/miniconda3/envs/stgat/lib/python3.7/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [21]:
torch.get_num_threads()

32

In [23]:
import psutil
for i, percentage in enumerate(psutil.cpu_percent(percpu=True, interval=1)):
    print(f"Core {i}: {percentage}%")

Core 0: 1.0%
Core 1: 0.0%
Core 2: 1.0%
Core 3: 1.0%
Core 4: 87.0%
Core 5: 0.0%
Core 6: 0.0%
Core 7: 0.0%
Core 8: 0.0%
Core 9: 0.0%
Core 10: 0.0%
Core 11: 0.0%
Core 12: 0.0%
Core 13: 0.0%
Core 14: 0.0%
Core 15: 0.0%
Core 16: 0.0%
Core 17: 0.0%
Core 18: 0.0%
Core 19: 0.0%
Core 20: 14.0%
Core 21: 0.0%
Core 22: 0.0%
Core 23: 1.0%
Core 24: 0.0%
Core 25: 0.0%
Core 26: 0.0%
Core 27: 0.0%
Core 28: 0.0%
Core 29: 0.0%
Core 30: 0.0%
Core 31: 0.0%


In [1]:
for i in range (1):
    print(i)

0


In [11]:
import torch
x = torch.tensor([[1, 2, 3],[1,2,3]])
x.repeat((4, ))

RuntimeError: Number of dimensions of repeat dims can not be smaller than number of dimensions of tensor

In [5]:
torch.randn(1, 3, 4).flatten(0,2).shape

IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)

In [3]:
import torch

/home/ssukup/miniconda3/envs/stgat/lib/python3.7/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [7]:
log_probs=torch.Tensor([1,2,3,4,5,6,7,8])
log_probs

tensor([1., 2., 3., 4., 5., 6., 7., 8.])

In [23]:
rewards=[torch.tensor([1]),torch.tensor([1]),torch.tensor([1]),torch.tensor([1])]
b=torch.cat(rewards, dim=0)
b

tensor([1, 1, 1, 1])

In [70]:
all_data_tensor = torch.empty((0, 25), dtype=torch.float32)
all_data_tensor

tensor([], size=(0, 25))

In [69]:
a=torch.empty(1)
a

tensor([-1.9005e-36])

In [61]:
a=a+1
a.reshape([1])

tensor([1.])

In [4]:
a=torch.tensor([0.5292, 0.5272, 0.5750, 0.5357, 0.5145, 0.5318, 0.5368, 0.5093, 0.4998,
        0.4895, 0.4824, 0.4275, 0.4477, 0.2645, 0.3094, 0.2610, 0.2635, 0.2786,
        0.2872, 0.2559, 0.2783, 0.3031, 0.2929, 0.2969, 0.3170, 0.2687, 0.3144,
        0.3153, 0.3299, 0.1654, 0.2031, 0.1840, 0.2236, 0.2154, 0.2316, 0.2699,
        0.2481, 0.2752, 0.2808, 0.2893, 0.2649, 0.3723, 0.3923, 0.4653, 0.4375,
        0.3743, 0.3682, 0.3790, 0.2953, 0.3283, 0.3126, 0.3625, 0.2528, 0.2860,
        0.1701, 0.2017, 0.1957, 0.2135, 0.1673, 0.1927, 0.1581, 0.1736, 0.1537,
        0.1578])
b=torch.tensor([-31.4396,  12.1054, -19.3717, -61.1767,  16.2774,   8.6281,  23.7225,
        -79.7146,   8.9092,  45.9172,  -4.5268, -91.6369,  27.8417,  50.4184,
          9.8164,  37.5233,  26.4580,  35.9668,  19.6348, -13.9678, -27.1077,
         -7.2022,  54.5566,  31.6552,  71.7911,   7.1745,  42.3522,   2.5435,
         30.3351,   9.4671,  24.3187,  19.4775,   6.5775,  26.6640,   3.5931,
         36.3142,  26.8261, -20.4469,  14.5940, -10.9031,  18.0776,  34.7328,
         38.0984,  46.2268,  22.5538, -27.9273,  25.2599, -18.9143,  16.5447,
        -38.6526, -73.4064,  44.6901,  72.9768,   1.2040,  19.1314, -14.3778,
         31.1580,  11.4526,  59.0418, -59.7119,   7.8531,   1.6888, -27.6418,
         50.7246])

In [6]:
(a*b).mean()

tensor(2.2044)

In [83]:
list_=torch.tensor([torch.tensor([1])]*4)

In [84]:
list_*list_

tensor([1, 1, 1, 1])

In [78]:
a=torch.cat((a, torch.tensor([1])), 0)
a

tensor([-1.9005e-36,  1.0000e+00,  1.0000e+00,  1.0000e+00])

In [ ]:
list

In [6]:
_l2_loss_rel = torch.narrow(log_probs, 0, 0, 3 - 0).sum()
_l2_loss_rel

tensor(6.)